image:
  registry: ghcr.io
  repository: bgshacklett/swimctl
  tag: latest
  pullPolicy: Always


resources:
  limits:
    smarter-devices/i2c-1: 1
    smarter-devices/i2c-20: 1
    smarter-devices/i2c-21: 1
  requests:
    smarter-devices/i2c-1: 1
    smarter-devices/i2c-20: 1
    smarter-devices/i2c-21: 1


podSecurityContext:
  runAsUser: 1000 # UID
  runAsGroup: 1000 # GID
  fsGroup: 1000 # GID for volume permission
  supplementalGroups:
    - 994  # Add i2c group membership
           # TODO: find out why this changed from 998


deploymentStrategy: Recreate


env:
  - name: NODE_RED_ENABLE_PROJECTS
    value: 'true'

  - name: NODE_RED_ACTIVE_PROJECT
    value: swimctl-flows

  - name: GITHUB_TOKEN_FLOWS
    valueFrom:
      secretKeyRef:
        name: swimctl
        key: gh_token

  - name: GITHUB_OWNER_FLOWS
    valueFrom:
      secretKeyRef:
        name: swimctl
        key: gh_owner

  - name: GITHUB_REPO_NAME_FLOWS
    valueFrom:
      secretKeyRef:
        name: swimctl
        key: gh_repo_name

  - name: NODE_RED_CREDENTIAL_SECRET
    valueFrom:
      secretKeyRef:
        name: swimctl
        key: node_red_credential_secret


ingress:
  enabled: true
  hosts:
    - host: swimctl.local
      paths:
        - path: /
          pathType: ImplementationSpecific


settings:
  name: settings
  configMapName: node-red-settings


extraVolumeMounts:
  - name: node-red-projects-settings
    mountPath: /data/.config.projects.json
    subPath: .config.projects.json


extraVolumes:
  - name: node-red-projects-settings
    configMap:
      name: node-red-projects-settings


initContainers:
  - name: clone-repo
    image: alpine/git # or any image that has git
    env:
      - name: GIT_REPO
        value: "https://github.com/bgshacklett/swimctl-flows.git"

      - name: GIT_VERSION
        value: "main"

    securityContext:
      runAsUser: 10003
      runAsGroup: 10003
    command:
    - /bin/sh
    - -c
    - |
      #!/bin/sh
      rm -rf /data/projects/* &&
      git clone $(GIT_REPO) /data/projects/swimctl-flows &&
      cd /data/projects/swimctl-flows &&
      git checkout $(GIT_VERSION)

      # Create post-commit hook
      cat << 'EOF' > .git/hooks/post-commit
      #!/bin/bash
      commit_hash=$(git rev-parse HEAD)
      patch_content=$(git format-patch -1 $commit_hash --stdout | base64 | awk '{printf "%s\\n", $0}' )
      url="https://api.github.com/repos/$GITHUB_OWNER_FLOWS/$GITHUB_REPO_NAME_FLOWS/actions/workflows/apply-patch.yml/dispatches"
      curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer $GITHUB_TOKEN_FLOWS" \
        "$url" \
        -d "{\"ref\":\"main\", \"inputs\": {\"patchContent\": \"$patch_content\"}}"
      EOF
      chmod +x .git/hooks/post-commit
      #end-range
    volumeMounts:
    - mountPath: /data
      name: data
