#!/bin/sh

log "Setting-up minimal environment"

# Retrieve WiFi config from wpa_supplicant.conf
INTERFACESOPTS_SSID="$(grep '^\sssid=' wpa_supplicant.conf \
											 | cut -d = f 2 \
											 | tr -d '"')"

INTERFACESOPTS_PSK="$(grep '^\spsk=' wpa_supplicant.conf | cut -d = f 2)"


cat <<-EOF > /tmp/ANSWERFILE
	# base answer file for setup-alpine script
	# generated by unattended.sh

	KEYMAPOPTS="us us"

	# Keep hostname
	HOSTNAMEOPTS="$(hostname)"

	# Set device manager to mdev
	DEVDOPTS=mdev

	# Contents of /etc/network/interfaces
	INTERFACESOPTS="auto lo
	iface lo inet loopback
	
	auto wlan0
	iface wlan0 inet dhcp
			wpa-ssid ${INTERFACESOPTS_SSID}
			wpa-psk  ${INTERFACESOPTS_PSK}"
	
	# Set timezone to local time. This device performs tasks on a schedule, and
	# keeping it in the local time zone makes more sense than using an offset.
	TIMEZONEOPTS="-z America/New_York"

	# Add first mirror (CDN)
	APKREPOSOPTS="-1"

	# Do not create any user
	USEROPTS=none

	# No Openssh
	SSHDOPTS="-c openssh"

	# Use openntpd
	NTPOPTS="chrony"

	# No disk install (diskless)
	DISKOPTS=none

	# Setup storage for diskless (find boot directory in
	# /media/xxxx/apk/.boot_repository)
	LBUOPTS="$(find /media \
						 -maxdepth 3 \
						 -type d \
						 -path '*/.*' \
						 -prune -o \
						 -type f \
						 -name '.boot_repository' \
						 -exec dirname {} \; \
						 | head -1 \
						 | xargs dirname)"

	APKCACHEOPTS="\$LBUOPTS/cache"
	EOF
